# Generated by Django 5.1.3 on 2024-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_lga_date_entered_lga_entered_by_user_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.DateTimeField(default='now'),
        ),
    ]
